safe: true
lsi: false
pygments: true
name: Thomas Reggi's Blog
description: A blog reguarding many things.
url: http://reggi.github.com/blog/
baseurl: http://reggi.github.com/blog/
auto: true
permalink: pretty